### ISSUE TITLE
Issue on upload file from another url

### ISSUE THREAD

**Issue by Lazhari** [OCFiles/ocfiles-server#6]
When i try to upload a file from another URL I get this error
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:443
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by atouchsh** [comment]
@Lazhari issue reproduced will push a fix
